### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by J4CKHunter** [aliatillaydemir/RadioApp#5]
- [ ]  app flow : 
<pre>
app -> send permanent notifications -> close screen
open screen -> click permanent notification button 
send fullscreen notification -> buttonlarla istediğini yap -> geriye basılırsa radyo dursun
tekrar permanent notification'a basılınca yeniden fullscreen notification yollanır ve eskisi silinir, 
</pre>

- [ ] fullscreen notification'un ufak notification'u için template hazırla yazı text felan yani
- [ ] ?? fullscreen notification'da activity yerine custom layout gösterilebilir mi?
- [ ] ?? butonlara basarken titreşim ekleyebilir miyiz ??
